// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package registry

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3c9d2b01DecodeGithubComDialogsDialogGoLibKafkaRegistry(in *jlexer.Lexer, out *ReqSubject) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "schema":
			out.Schema = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGithubComDialogsDialogGoLibKafkaRegistry(out *jwriter.Writer, in ReqSubject) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"schema\":"
		out.RawString(prefix[1:])
		out.String(string(in.Schema))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ReqSubject) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGithubComDialogsDialogGoLibKafkaRegistry(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ReqSubject) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGithubComDialogsDialogGoLibKafkaRegistry(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ReqSubject) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGithubComDialogsDialogGoLibKafkaRegistry(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ReqSubject) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGithubComDialogsDialogGoLibKafkaRegistry(l, v)
}
func easyjson3c9d2b01DecodeGithubComDialogsDialogGoLibKafkaRegistry1(in *jlexer.Lexer, out *ReqConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "compatibility":
			out.Compatibility = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGithubComDialogsDialogGoLibKafkaRegistry1(out *jwriter.Writer, in ReqConfig) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"compatibility\":"
		out.RawString(prefix[1:])
		out.String(string(in.Compatibility))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ReqConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGithubComDialogsDialogGoLibKafkaRegistry1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ReqConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGithubComDialogsDialogGoLibKafkaRegistry1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ReqConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGithubComDialogsDialogGoLibKafkaRegistry1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ReqConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGithubComDialogsDialogGoLibKafkaRegistry1(l, v)
}
